# SPDX-FileCopyrightText: 2026 Daniel Mohr
#
# SPDX-License-Identifier: GPL-3.0-or-later

variables:
  DEBIAN_FRONTEND: noninteractive
  APT_GET_INSTALL: "apt-get install --no-install-recommends -q -y"

.display_env:
  before_script:
    - date
    - uname -a
    - cat /etc/os-release

pre-commit:
  stage: .pre
  image:
    name: alpine:latest
  extends: .display_env
  script:
    - apk add --no-cache git npm pre-commit
    - pre-commit --version
    - pre-commit run --all-files --show-diff-on-failure
    - pre-commit autoupdate --jobs 0
    - git diff .pre-commit-config.yaml

build_pages:
  stage: build
  variables:
    DEBIAN_FRONTEND: noninteractive
    JEKYLL_ENV: production
    APT_GET_INSTALL: "apt-get install --no-install-recommends -q -y"
  image:
    # https://hub.docker.com/_/ruby
    name: ruby:latest
    entrypoint: [""]
  extends: .display_env
  script:
    - set -x
    - apt-get update
    - $APT_GET_INSTALL nodejs
    - (cd "site" && gem install bundler)
    - (cd "site" && bundler install)
    - (cd "site" && jekyll build -d ../public)
    - ruby -v
    - gem -v
    - jekyll -v
    - find public/
  artifacts:
    paths:
      - public/

pages:
  stage: deploy
  image:
    name: alpine:latest
  pages: true
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PROJECT_ID == "81882967" && $CI_SERVER_HOST == "gitlab.com"'
      when: always
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_PROJECT_ID == "81882967" && $CI_SERVER_HOST == "gitlab.com"'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      when: manual
    - when: never
  extends: .display_env
  script:
    - find public/
