# SPDX-FileCopyrightText: 2026 COMPACT-for-space contributors
#
# SPDX-License-Identifier: CC-BY-SA-4.0

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pdfs/$TAG"
  DEBIAN_FRONTEND: noninteractive
  APT_GET_INSTALL: "apt-get install --no-install-recommends -q -y"
  BASE_NAME: "COMPACT_in_space"
  JEKYLL_ENV: production

.display_env:
  before_script:
    - date
    - uname -a
    - cat /etc/os-release

pre-commit:
  stage: .pre
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
    - when: never
  image:
    name: alpine:latest
  extends: .display_env
  script:
    - apk add --no-cache git jq pre-commit
    - pre-commit --version
    - pre-commit run --all-files --show-diff-on-failure
    - pre-commit autoupdate --jobs 0
    - git diff .pre-commit-config.yaml
    - jq < metadata.json

prepare_release_step0:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline" && $STEP == "2"
      when: always
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && ($CI_PROJECT_ID == "81882967" || $CI_PROJECT_ID == "81990844") && $CI_SERVER_HOST == "gitlab.com" && $CI_PIPELINE_SOURCE != "pipeline"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
    - when: never
  image:
    name: alpine:latest
  extends: .display_env
  script:
    - apk add --no-cache git jq
    - TAG="$(jq -r .metadata.version metadata.json)"
    - DESCRIPTION="$(jq -r .metadata.description metadata.json)"
    - DEPLOY2ZENODO_UPLOAD="$TAG.zip"
    - git archive --format zip --output "$BASE_NAME"."$TAG".zip "$CI_COMMIT_SHA"
    - |
      {
      echo "DESCRIPTION=$DESCRIPTION"
      echo "TAG=$TAG"
      echo "DEPLOY2ZENODO_UPLOAD=$DEPLOY2ZENODO_UPLOAD"
      }  | tee variables.env
  artifacts:
    paths:
      - "$BASE_NAME.$TAG.zip"
    reports:
      dotenv: variables.env

prepare_release_step1:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && ($CI_PROJECT_ID == "81882967" || $CI_PROJECT_ID == "81990844") && $CI_SERVER_HOST == "gitlab.com" && $CI_PIPELINE_SOURCE != "pipeline"
  needs:
    - job: prepare_release_step0
      artifacts: true
  inherit:
    variables: false
  variables:
    STEP: "1"
    TAG: $TAG
    TAG_COMMIT_SHA: $CI_COMMIT_SHA
    TAG_COMMIT_TIMESTAMP: $TAG_COMMIT_TIMESTAMP
    DESCRIPTION: $DESCRIPTION
    DEPLOY2ZENODO_UPLOAD: $DEPLOY2ZENODO_UPLOAD
  trigger:
    project: daniel_mohr/deploy_compact-for-space_to_zenodo
    strategy: depend
    forward:
      yaml_variables: true
      pipeline_variables: false

build_pages:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
    - when: never
  image:
    # https://hub.docker.com/_/ruby
    # based on debian
    name: ruby:latest
    entrypoint: [""]
  extends: .display_env
  script:
    - apt-get update
    - $APT_GET_INSTALL pre-commit
    - pre-commit --version
    - pre-commit run --all-files --show-diff-on-failure --config .pre-commit-config.rubocop.yaml
    - pre-commit autoupdate --jobs 0 --config .pre-commit-config.rubocop.yaml
    - git diff .pre-commit-config.rubocop.yaml
    - (cd "site" && gem install bundler)
    - (cd "site" && bundler install)
    - ruby -v
    - gem -v
    - jekyll -v
    - (cd "site" && jekyll build -d ../public)
    - $APT_GET_INSTALL chromium img2pdf poppler-utils
    - chromium --version
    - (cd "site" && bundle exec jekyll serve --host 0.0.0.0 --quiet --detach)
    - until curl -f -s http://localhost:4000/ > /dev/null; do sleep 1; done
    - sleep 1
    - mkdir -p pdfs
    - |
      FILES=(
      "00_index:index"
      "01_science:science-mission"
      "02_design:realization-design"
      "03_activities:breadboard"
      "04_docu:documentation-specification"
      "05_posts:posts"
      "06_publications:publications"
      "07_funding:funding"
      "08_about:about")
    - echo "127.0.0.1 site-2ef4a3.gitlab.io" >> /etc/hosts
    - set -x
    - |
      for item in "${FILES[@]}"; do
      idx=${item%%:*}
      path=${item##*:}
      echo "idx: $idx"
      echo "path: $path"
      if [ "$path" = "index" ]; then
      # url="http://localhost:4000/"
      url="http://site-2ef4a3.gitlab.io:4000/"
      else
      # url="http://localhost:4000/${path}"
      url="http://site-2ef4a3.gitlab.io:4000/${path}"
      fi
      chromium --no-sandbox --disable-dev-shm-usage --headless --disable-gpu --page=A4 --print-to-pdf="$(pwd)"/pdfs/"${idx}".pdf "$url"
      if [ "$path" = "index" ]; then
      chromium --no-sandbox --disable-dev-shm-usage --headless --disable-gpu --screenshot="$(pwd)"/pdfs/"${idx}".png --window-size=1024,768 "$url"
      fi
      done
    - img2pdf --output pdfs/00_cover.pdf -S Letter pdfs/00_index.png
    - pdfunite pdfs/*.pdf "$BASE_NAME"."$TAG".pdf
    - rm -r pdfs
    - pkill -f "jekyll serve"
    - find public/
  artifacts:
    paths:
      - public/
      - "$BASE_NAME.$TAG.pdf"

build_pages_for_release:
  # triggered by: https://gitlab.com/daniel_mohr/compact-for-space-site
  extends: build_pages
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline" && $STEP == "2"
  needs:
    - job: prepare_release_step0
      artifacts: true
  variables:
    TAG: $TAG
    TAG_COMMIT_SHA: $TAG_COMMIT_SHA
    TAG_COMMIT_TIMESTAMP: $TAG_COMMIT_TIMESTAMP
    STEP: "2"
    DOI: $DOI
    DEPLOY2INVENIORDM_DEPOSITION_ID: $DEPLOY2INVENIORDM_DEPOSITION_ID
    PARENTDOI: $PARENTDOI
  before_script:
    - echo "TAG=$TAG"
    - echo "TAG_COMMIT_SHA=$TAG_COMMIT_SHA"
    - echo "TAG_COMMIT_TIMESTAMP=$TAG_COMMIT_TIMESTAMP"
    - echo "DOI=$DOI"
    - echo "DEPLOY2INVENIORDM_DEPOSITION_ID=$DEPLOY2INVENIORDM_DEPOSITION_ID"
    - echo "PARENTDOI=$PARENTDOI"

prepare_release_job:
  # triggered by: https://gitlab.com/daniel_mohr/compact-for-space-site
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline" && $STEP == "2"
  needs:
    - job: build_pages_for_release
      artifacts: true
  image:
    name: alpine:latest
  extends: .display_env
  script:
    - env
    - apk add --no-cache curl
    - |
      echo "upload-file: $BASE_NAME.$TAG.pdf"
      echo "url: $PACKAGE_REGISTRY_URL/$BASE_NAME.$TAG.pdf"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "$BASE_NAME.$TAG.pdf" "$PACKAGE_REGISTRY_URL/$BASE_NAME.$TAG.pdf"

release_job:
  # triggered by: https://gitlab.com/daniel_mohr/compact-for-space-site
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "pipeline" && $STEP == "2"
  variables:
    TAG: $TAG
    TAG_COMMIT_SHA: $TAG_COMMIT_SHA
    TAG_COMMIT_TIMESTAMP: $TAG_COMMIT_TIMESTAMP
    STEP: "2"
    DOI: $DOI
    DEPLOY2INVENIORDM_DEPOSITION_ID: $DEPLOY2INVENIORDM_DEPOSITION_ID
    PARENTDOI: $PARENTDOI
  needs:
    - job: prepare_release_step0
      artifacts: true
    - job: prepare_release_job
    - job: build_pages_for_release
      artifacts: true
  image:
    registry.gitlab.com/gitlab-org/release-cli:latest
  before_script:
    - test -n "$DESCRIPTION"
  script:
    - cat /etc/os-release
    - echo "running release_job for $TAG"
    - wget "https://zenodo.org/badge/DOI/$DOI.svg"
  release:
    name: '$TAG'
    description: '$DESCRIPTION'
    tag_name: '$TAG'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: "$BASE_NAME.$TAG.pdf"
          filepath: "/$BASE_NAME.$TAG.pdf"
          url: "$PACKAGE_REGISTRY_URL/$BASE_NAME.$TAG.pdf"
          link_type: other
  artifacts:
    paths:
      - "$DOI.svg"

post_release_job:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "pipeline" && $STEP == "2"
  needs:
    - job: release_job
  variables:
    TAG: $TAG
    TAG_COMMIT_SHA: $TAG_COMMIT_SHA
    TAG_COMMIT_TIMESTAMP: $TAG_COMMIT_TIMESTAMP
    STEP: "3"
    DOI: $DOI
    DEPLOY2INVENIORDM_DEPOSITION_ID: $DEPLOY2INVENIORDM_DEPOSITION_ID
    PARENTDOI: $PARENTDOI
  trigger:
    project: daniel_mohr/deploy_compact-for-space_to_zenodo
    strategy: depend
    forward:
      yaml_variables: true
      pipeline_variables: false

pages:
  stage: deploy
  image:
    name: alpine:latest
  pages: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
      when: never
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_PROJECT_ID == "81882967" && $CI_SERVER_HOST == "gitlab.com"'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      when: manual
    - when: never
  extends: .display_env
  script:
    - find public/

pages_after_release:
  # triggered by: https://gitlab.com/daniel_mohr/compact-for-space-site
  extends: pages
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline" && $STEP == "2"
  needs:
    - job: build_pages_for_release
      artifacts: true
