# SPDX-FileCopyrightText: 2026 COMPACT-for-space contributors
#
# SPDX-License-Identifier: CC-BY-SA-4.0

repos:
  - repo: https://github.com/rubocop/rubocop
    rev: v1.91.0
    hooks:
      - id: rubocop
        args: [--config=.rubocop.yaml]
